-- Create Stories table to store generated book content
CREATE TABLE IF NOT EXISTS "Stories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  "book_id" UUID NOT NULL REFERENCES "Books" ("id") ON DELETE CASCADE,
  "call_id" BIGINT, -- Optional reference to the Call ID if available
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL
);

-- Safely add columns if they don't exist (Idempotent migration)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Stories' AND column_name = 'chapter_number') THEN
        ALTER TABLE "Stories" ADD COLUMN "chapter_number" INTEGER DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Stories' AND column_name = 'status') THEN
        ALTER TABLE "Stories" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'draft';
    END IF;

    -- Also ensure Books table has chapter_count
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Books' AND column_name = 'chapter_count') THEN
        ALTER TABLE "Books" ADD COLUMN "chapter_count" INTEGER DEFAULT 0;
    END IF;
END $$;

-- Enable RLS
ALTER TABLE "Stories" ENABLE ROW LEVEL SECURITY;

-- Re-create Policies (Drop first to avoid 'already exists' error)
DROP POLICY IF EXISTS "Enable read access for all users" ON "Stories";
CREATE POLICY "Enable read access for all users" ON "Stories" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "Stories";
CREATE POLICY "Enable insert for authenticated users only" ON "Stories" FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "Stories";
CREATE POLICY "Enable update for authenticated users only" ON "Stories" FOR UPDATE TO authenticated USING (true);

