-- 1. Create BookPhotos table
-- Changed book_id to UUID to match Books table
CREATE TABLE IF NOT EXISTS "BookPhotos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" UUID NOT NULL REFERENCES "Books" ("id") ON DELETE CASCADE,
  "image_url" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create a storage bucket for book photos
DO $$
BEGIN
    INSERT INTO storage.buckets (id, name, public) 
    VALUES ('book-photos', 'book-photos', true);
EXCEPTION WHEN unique_violation THEN
    NULL; -- Bucket already exists
END $$;

-- 3. Set up Row Level Security (RLS) for the bucket
-- Allow public access to view images
CREATE POLICY "Public Access Photos"
ON storage.objects FOR SELECT
USING ( bucket_id = 'book-photos' );

-- Allow authenticated users to upload images
CREATE POLICY "Authenticated Upload Photos"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'book-photos' );

-- Allow users to update their own images
CREATE POLICY "Authenticated Update Photos"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'book-photos' );

-- 4. Enable RLS on the table (Optional, for stricter security)
ALTER TABLE "BookPhotos" ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone 
-- (If you want to restrict to specific users, adjust the USING clause)
CREATE POLICY "Enable read access for all users" ON "BookPhotos" FOR SELECT USING (true);

-- Allow insert access to authenticated users
CREATE POLICY "Enable insert for authenticated users only" ON "BookPhotos" FOR INSERT TO authenticated WITH CHECK (true);
